# The regex used is a bit different from original documenation:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Original documentation implies that the __init__.py only has one line with __version__
---
{% set version_match = load_file_regex(load_file="ddf_peakachu/__init__.py", 
regex_pattern='(?:.*)__version__ = "(.+)"') %}

{% set version = version_match[1] %}


package:
        name: ddf_peakachu
        version: {{ version }}

source:
        path: ../

requirements:
        build:
                - python
                - setuptools
        run:
                - python >=3.9

about:
        home: https://github.com/TimoDiepers/dds_peakachu
        license: BSD-3-Clause
        license_file: LICENSE

build:
        noarch: python
        script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
